### ISSUE TITLE
is there a really action video of it ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion-esp8266#1]
how can esp8266 handle fluxion and where does the handshake file goes ... it's memory is 512 kb ...!!! @MPX4132

**Comment by deltaxflux** [comment]
At the moment we don't capture a handshake to prove it but I maybe we can strip the cap so that keep it on a minimum.

**Comment by minanagehsalalma** [comment]
@MPX4132 ok thanks
